<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Ot.PSampleVerificationTracker.Api</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.12"/>
        <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Ot.SampleVerificationTracker.Common\Ot.SampleVerificationTracker.Common.csproj" />
    </ItemGroup>

</Project>
